begin;

set local lock_timeout = '10s';
set local statement_timeout = '60s';

alter table public.nuvemshop_conexoes
  add column if not exists escrita_habilitada_ate timestamp with time zone,
  add column if not exists escrita_simulacao_id uuid;

-- Toda instalacao desta protecao comeca fechada, mesmo que um teste anterior
-- tenha deixado o interruptor manual ligado.
update public.nuvemshop_conexoes
set escrita_habilitada = false,
    escrita_habilitada_em = null,
    escrita_habilitada_por = null,
    escrita_habilitada_ate = null,
    escrita_simulacao_id = null
where escrita_habilitada
   or escrita_habilitada_em is not null
   or escrita_habilitada_por is not null
   or escrita_habilitada_ate is not null
   or escrita_simulacao_id is not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'nuvemshop_conexoes_escrita_simulacao_fkey'
      and conrelid = 'public.nuvemshop_conexoes'::regclass
  ) then
    alter table public.nuvemshop_conexoes
      add constraint nuvemshop_conexoes_escrita_simulacao_fkey
      foreign key (escrita_simulacao_id)
      references public.nuvemshop_sincronizacoes(id)
      on delete restrict;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'nuvemshop_conexoes_janela_piloto_check'
      and conrelid = 'public.nuvemshop_conexoes'::regclass
  ) then
    alter table public.nuvemshop_conexoes
      add constraint nuvemshop_conexoes_janela_piloto_check
      check (
        not escrita_habilitada
        or (
          escrita_habilitada_em is not null
          and escrita_habilitada_ate is not null
          and escrita_habilitada_ate > escrita_habilitada_em
          and escrita_habilitada_ate <= escrita_habilitada_em + interval '5 minutes'
          and escrita_simulacao_id is not null
        )
      );
  end if;
end;
$$;

comment on column public.nuvemshop_conexoes.escrita_habilitada_ate is
  'Fim da janela temporaria de escrita do piloto. A janela nunca pode exceder cinco minutos.';
comment on column public.nuvemshop_conexoes.escrita_simulacao_id is
  'Simulacao exata autorizada pela janela temporaria do piloto.';

create table if not exists public.nuvemshop_janelas_escrita (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.nuvemshop_conexoes(store_id) on delete restrict,
  simulacao_id uuid references public.nuvemshop_sincronizacoes(id) on delete restrict,
  acao text not null check (
    acao in ('habilitada', 'desabilitada', 'aplicacao_finalizada')
  ),
  solicitado_por uuid references auth.users(id) on delete restrict,
  habilitada_ate timestamp with time zone,
  created_at timestamp with time zone not null default now()
);

create index if not exists nuvemshop_janelas_escrita_store_created_idx
on public.nuvemshop_janelas_escrita (store_id, created_at desc);

alter table public.nuvemshop_janelas_escrita enable row level security;

revoke all on public.nuvemshop_janelas_escrita from public;
revoke all on public.nuvemshop_janelas_escrita from anon;
revoke all on public.nuvemshop_janelas_escrita from authenticated;

create or replace function public.configurar_janela_piloto_nuvemshop(
  p_store_id bigint,
  p_simulacao_id uuid,
  p_solicitado_por uuid,
  p_habilitar boolean,
  p_confirmacao text default null
)
returns timestamp with time zone
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_conexao public.nuvemshop_conexoes%rowtype;
  v_simulacao public.nuvemshop_sincronizacoes%rowtype;
  v_habilitada_ate timestamp with time zone;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'A janela do piloto so pode ser configurada pelo servidor.'
      using errcode = '42501';
  end if;

  if p_store_id is null
     or p_solicitado_por is null
     or p_habilitar is null then
    raise exception 'Parametros obrigatorios da janela do piloto ausentes.';
  end if;

  if not exists (
    select 1
    from public.perfis p
    where p.user_id = p_solicitado_por
      and p.tipo = 'admin'
  ) then
    raise exception 'Solicitante nao e administrador.'
      using errcode = '42501';
  end if;

  select c.*
    into v_conexao
  from public.nuvemshop_conexoes c
  where c.store_id = p_store_id
  for update;

  if not found then
    raise exception 'Conexao Nuvemshop nao encontrada.';
  end if;

  if not p_habilitar then
    update public.nuvemshop_conexoes
    set escrita_habilitada = false,
        escrita_habilitada_em = null,
        escrita_habilitada_por = null,
        escrita_habilitada_ate = null,
        escrita_simulacao_id = null
    where store_id = p_store_id;

    insert into public.nuvemshop_janelas_escrita (
      store_id,
      simulacao_id,
      acao,
      solicitado_por
    ) values (
      p_store_id,
      p_simulacao_id,
      'desabilitada',
      p_solicitado_por
    );

    return null;
  end if;

  if p_confirmacao is distinct from 'LIBERAR PILOTO POR 5 MINUTOS' then
    raise exception 'Confirmacao da janela do piloto invalida.';
  end if;

  if p_simulacao_id is null then
    raise exception 'Informe a simulacao que autorizara a janela.';
  end if;

  if v_conexao.escrita_habilitada
     and v_conexao.escrita_habilitada_ate > clock_timestamp() then
    raise exception 'Ja existe uma janela temporaria ativa para esta loja.';
  end if;

  if v_conexao.limite_aplicacao <> 1 then
    raise exception 'O piloto exige limite de exatamente um item.';
  end if;

  if nullif(btrim(v_conexao.local_estoque_id), '') is null then
    raise exception 'Local de estoque da loja nao esta confirmado.';
  end if;

  if not exists (
    select 1
    from regexp_split_to_table(
      coalesce(v_conexao.escopos, ''),
      '[[:space:],]+'
    ) as escopo(valor)
    where lower(escopo.valor) = 'write_products'
  ) then
    raise exception 'A conexao nao possui o escopo write_products.'
      using errcode = '42501';
  end if;

  select s.*
    into v_simulacao
  from public.nuvemshop_sincronizacoes s
  where s.id = p_simulacao_id
  for update;

  if not found
     or v_simulacao.modo <> 'simulacao'
     or v_simulacao.status <> 'concluida'
     or v_simulacao.total_itens < 1
     or v_simulacao.itens_sucesso <> v_simulacao.total_itens
     or v_simulacao.itens_falha <> 0
     or v_simulacao.concluido_em is null
     or v_simulacao.store_id <> p_store_id
     or v_simulacao.solicitado_por <> p_solicitado_por
     or v_simulacao.local_estoque_id is distinct from v_conexao.local_estoque_id
     or v_simulacao.created_at < now() - interval '15 minutes'
     or v_simulacao.created_at > now() + interval '1 minute' then
    raise exception 'A simulacao nao atende aos requisitos da janela do piloto.';
  end if;

  if exists (
    select 1
    from public.nuvemshop_sincronizacoes s
    where s.modo = 'aplicacao'
      and s.origem_simulacao_id = p_simulacao_id
  ) then
    raise exception 'Esta simulacao ja originou uma aplicacao.';
  end if;

  if exists (
    select 1
    from public.nuvemshop_sincronizacoes s
    where s.store_id = p_store_id
      and s.modo = 'aplicacao'
      and s.status in ('preparando', 'processando')
  ) then
    raise exception 'Existe uma aplicacao desta loja ainda em processamento.';
  end if;

  v_habilitada_ate := clock_timestamp() + interval '5 minutes';

  update public.nuvemshop_conexoes
  set escrita_habilitada = true,
      escrita_habilitada_em = clock_timestamp(),
      escrita_habilitada_ate = v_habilitada_ate,
      escrita_habilitada_por = p_solicitado_por,
      escrita_simulacao_id = p_simulacao_id,
      limite_aplicacao = 1
  where store_id = p_store_id;

  insert into public.nuvemshop_janelas_escrita (
    store_id,
    simulacao_id,
    acao,
    solicitado_por,
    habilitada_ate
  ) values (
    p_store_id,
    p_simulacao_id,
    'habilitada',
    p_solicitado_por,
    v_habilitada_ate
  );

  return v_habilitada_ate;
end;
$$;

create or replace function public.validar_janela_antes_aplicacao_nuvemshop()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_conexao public.nuvemshop_conexoes%rowtype;
begin
  if new.modo <> 'aplicacao' then
    return new;
  end if;

  select c.*
    into v_conexao
  from public.nuvemshop_conexoes c
  where c.store_id = new.store_id
  for update;

  if not found
     or not v_conexao.escrita_habilitada
     or v_conexao.escrita_habilitada_ate is null
     or v_conexao.escrita_habilitada_ate <= clock_timestamp()
     or v_conexao.limite_aplicacao <> 1
     or new.origem_simulacao_id is distinct from v_conexao.escrita_simulacao_id
     or new.solicitado_por is distinct from v_conexao.escrita_habilitada_por then
    raise exception 'A janela temporaria do piloto esta fechada ou expirada.'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

drop trigger if exists validar_janela_antes_aplicacao_nuvemshop
on public.nuvemshop_sincronizacoes;

create trigger validar_janela_antes_aplicacao_nuvemshop
before insert on public.nuvemshop_sincronizacoes
for each row execute function public.validar_janela_antes_aplicacao_nuvemshop();

create or replace function public.desligar_janela_apos_aplicacao_nuvemshop()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.modo = 'aplicacao'
     and new.status in ('concluida', 'parcial', 'falhou')
     and old.status is distinct from new.status then
    update public.nuvemshop_conexoes
    set escrita_habilitada = false,
        escrita_habilitada_em = null,
        escrita_habilitada_por = null,
        escrita_habilitada_ate = null,
        escrita_simulacao_id = null
    where store_id = new.store_id;

    insert into public.nuvemshop_janelas_escrita (
      store_id,
      simulacao_id,
      acao,
      solicitado_por
    ) values (
      new.store_id,
      new.origem_simulacao_id,
      'aplicacao_finalizada',
      new.solicitado_por
    );
  end if;

  return new;
end;
$$;

drop trigger if exists desligar_janela_apos_aplicacao_nuvemshop
on public.nuvemshop_sincronizacoes;

create trigger desligar_janela_apos_aplicacao_nuvemshop
after update of status on public.nuvemshop_sincronizacoes
for each row execute function public.desligar_janela_apos_aplicacao_nuvemshop();

revoke all on function public.configurar_janela_piloto_nuvemshop(
  bigint, uuid, uuid, boolean, text
) from public, anon, authenticated;

grant execute on function public.configurar_janela_piloto_nuvemshop(
  bigint, uuid, uuid, boolean, text
) to service_role;

revoke all on function public.validar_janela_antes_aplicacao_nuvemshop()
from public, anon, authenticated;

revoke all on function public.desligar_janela_apos_aplicacao_nuvemshop()
from public, anon, authenticated;

notify pgrst, 'reload schema';

commit;

select
  store_id,
  escopos,
  local_estoque_id,
  escrita_habilitada,
  escrita_habilitada_ate,
  escrita_simulacao_id,
  limite_aplicacao
from public.nuvemshop_conexoes
order by store_id;
